export const GET_JOGS_URL = 'api/v1/data/sync'
export const CREATE_JOG_URL = 'api/v1/data/jog'
export const CHANGE_JOG_URL = 'api/v1/data/jog'
export const GET_TOKEN_URL = 'api/v1/auth/uuidLogin'
export const GET_USER_DATA_URL = 'api/v1/auth/user'
