export const CHANGE_LOGIN_STATUS = 'CHANGE_LOGIN_STATUS'
export const SET_SELECTED_JOG_ID = 'SET_SELECTED_JOG_ID'
export const SET_NEW_JOGS = 'SET_NEW_JOGS'
export const SET_FILTER_STATUS = 'SET_FILTER_STATUS'